# Generated by Django 5.1.4 on 2025-01-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='core_services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='legal_structure',
            field=models.CharField(blank=True, choices=[('LLP', 'LLP'), ('Pvt Ltd', 'Private Limited'), ('Partnership', 'Partnership'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='portfolio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
