# Generated by Django 5.1.4 on 2025-02-01 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='salary',
            new_name='stipend',
        ),
        migrations.AddField(
            model_name='internship',
            name='min_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internship',
            name='required_qualification',
            field=models.CharField(choices=[('bachelor', 'Bachelors'), ('master', 'Masters'), ('phd', 'PhD'), ('diploma', 'Diploma')], default='bachelor', max_length=50),
        ),
        migrations.AddField(
            model_name='internship',
            name='required_skills',
            field=models.TextField(default='', help_text='Enter required skills separated by commas'),
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('degree', models.CharField(choices=[('bachelor', "Bachelor's"), ('master', 'Masters'), ('phd', 'PhD'), ('diploma', 'Diploma')], max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('work_experience', models.DecimalField(decimal_places=1, max_digits=4)),
                ('resume', models.FileField(upload_to='internship_resumes/')),
                ('skills', models.TextField()),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.internship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
