# Generated by Django 5.1.4 on 2025-01-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofile',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='industries_of_interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='key_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
