# Generated by Django 5.1.4 on 2025-01-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_individualprofile_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofile',
            name='certifications',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='hobbies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='industries_of_interest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='key_skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
