# Generated by Django 5.1.4 on 2025-02-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_salary_internship_stipend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='match_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
