# Generated by Django 5.1.4 on 2025-02-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_saveditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedItem',
        ),
    ]
