# Generated by Django 5.1.4 on 2025-01-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
