# Generated by Django 5.1.4 on 2025-01-15 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_internship_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Development', 'Development'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Writing', 'Writing'), ('Data Entry', 'Data Entry'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('skills_required', models.TextField()),
                ('duration', models.CharField(choices=[('Less than 1 month', 'Less than 1 month'), ('1-3 months', '1-3 months')], max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(choices=[('Milestone-based', 'Milestone-based'), ('Hourly', 'Hourly'), ('Fixed-price', 'Fixed-price')], max_length=50)),
                ('experience_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=50)),
                ('location_preference', models.CharField(blank=True, max_length=200, null=True)),
                ('language_requirements', models.CharField(blank=True, max_length=200, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('company_name', models.CharField(max_length=200)),
                ('company_description', models.TextField()),
                ('point_of_contact_name', models.CharField(max_length=100)),
                ('point_of_contact_email', models.EmailField(max_length=254)),
                ('point_of_contact_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
