# Generated by Django 5.1.4 on 2025-02-01 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_bookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'job')},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='core_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.coreopportunity'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.internship'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.job'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'core_opportunity'), ('user', 'internship'), ('user', 'job')},
        ),
    ]
