# Generated by Django 5.1.1 on 2025-01-17 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_freelanceproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('portfolio_links', models.TextField(help_text='Add your portfolio links (one per line)')),
                ('previous_works', models.TextField(help_text='Describe your relevant previous works')),
                ('expected_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timeline', models.CharField(max_length=100)),
                ('execution_plan', models.TextField(help_text='Describe how you plan to execute this project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='users.freelanceproject')),
            ],
        ),
    ]
