# Generated by Django 5.1.4 on 2025-02-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_bookmark_unique_together_bookmark_idea_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'core_opportunity'), ('user', 'idea'), ('user', 'internship'), ('user', 'job')},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='freelance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.freelanceproject'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'core_opportunity'), ('user', 'freelance'), ('user', 'idea'), ('user', 'internship'), ('user', 'job')},
        ),
    ]
