# Generated by Django 5.1.4 on 2025-01-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
