# Generated by Django 5.1.4 on 2025-02-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_bookmark_unique_together_bookmark_freelance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='pitch_deck',
            field=models.FileField(blank=True, null=True, upload_to='pitch_decks/'),
        ),
    ]
