# Generated by Django 5.1.4 on 2025-01-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_jobapplication_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='min_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='required_qualification',
            field=models.CharField(default='bachelor', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.TextField(default='', help_text='Enter required skills separated by commas'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.TextField(default='', help_text='Enter your skills separated by commas'),
        ),
    ]
