# Generated by Django 5.1.4 on 2025-01-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_job_min_experience_job_required_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='required_qualification',
            field=models.CharField(choices=[('bachelor', 'Bachelors'), ('master', 'Masters'), ('phd', 'PhD'), ('diploma', 'Diploma')], default='bachelor', max_length=50),
        ),
    ]
