# Generated by Django 5.1.4 on 2025-01-20 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_jobapplication_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.CreateModel(
            name='SavedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_match_score', models.FloatField(default=0.0)),
                ('matching_skills', models.TextField(blank=True, help_text='Comma-separated matching skills')),
                ('missing_skills', models.TextField(blank=True, help_text='Comma-separated missing skills')),
                ('category', models.CharField(default='Shortlisted', max_length=100)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
