# Generated by Django 5.1.4 on 2025-01-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_jobapplication_email_savedapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
