# Generated by Django 5.1.4 on 2025-01-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_likedislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='proposal',
        ),
        migrations.AddField(
            model_name='bid',
            name='certifications',
            field=models.FileField(blank=True, null=True, upload_to='bid_certifications/', verbose_name='Certifications'),
        ),
        migrations.AddField(
            model_name='bid',
            name='client_testimonials',
            field=models.TextField(blank=True, null=True, verbose_name='Client Testimonials/References'),
        ),
        migrations.AddField(
            model_name='bid',
            name='company_profile',
            field=models.TextField(blank=True, null=True, verbose_name='Company Profile'),
        ),
        migrations.AddField(
            model_name='bid',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bid',
            name='minimum_budget_expectation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Minimum Budget Expectation'),
        ),
        migrations.AddField(
            model_name='bid',
            name='payment_terms',
            field=models.TextField(blank=True, null=True, verbose_name='Payment Terms'),
        ),
        migrations.AddField(
            model_name='bid',
            name='portfolio_links',
            field=models.TextField(blank=True, null=True, verbose_name='Portfolio/Previous Work Links'),
        ),
        migrations.AddField(
            model_name='bid',
            name='preferred_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='project_approach',
            field=models.TextField(blank=True, null=True, verbose_name='Project Approach'),
        ),
        migrations.AddField(
            model_name='bid',
            name='proposal_document',
            field=models.FileField(blank=True, null=True, upload_to='bid_proposals/', verbose_name='Proposal Document'),
        ),
        migrations.AddField(
            model_name='bid',
            name='team_resources',
            field=models.TextField(blank=True, null=True, verbose_name='Team/Resources Description'),
        ),
        migrations.AddField(
            model_name='bid',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Proposed Price'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='estimated_timeline',
            field=models.IntegerField(blank=True, help_text='Estimated days to complete', null=True),
        ),
    ]
