# Generated by Django 5.1.4 on 2025-01-22 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_bid_certifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Opportunity Title')),
                ('role_details', models.TextField(verbose_name='Role Details')),
                ('responsibilities', models.TextField()),
                ('key_objectives', models.TextField(verbose_name='Key Objectives')),
                ('expertise', models.CharField(max_length=200, verbose_name='Preferred Qualifications')),
                ('benefits', models.TextField(blank=True, verbose_name='Other Benefits')),
                ('opportunity_type', models.CharField(choices=[('Co-Founder Role', 'Co-Founder Role'), ('Advisor', 'Advisor'), ('Investor Partnership', 'Investor Partnership'), ('Team Member', 'Team Member'), ('Other', 'Other')], max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Description of Opportunity')),
                ('stage', models.CharField(choices=[('Idea Stage', 'Idea Stage'), ('Prototype Ready', 'Prototype Ready'), ('MVP Launched', 'MVP Launched'), ('Scaling', 'Scaling')], max_length=50)),
                ('company_mission', models.TextField()),
                ('requirements', models.CharField(max_length=200, verbose_name='Required Skills')),
                ('future_plans', models.TextField()),
                ('compensation_model', models.CharField(choices=[('Equity-Based', 'Equity-Based'), ('Paid Opportunity', 'Paid Opportunity'), ('Other', 'Other')], max_length=50)),
                ('equity_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('other_compensation', models.CharField(blank=True, max_length=200, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('location_preference', models.CharField(choices=[('Remote', 'Remote'), ('In-Person', 'In-Person'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('location_details', models.CharField(blank=True, max_length=200, null=True)),
                ('commitment', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Flexible', 'Flexible')], max_length=50)),
                ('requires_nda', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
