# Generated by Django 5.1.4 on 2025-01-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_title', models.CharField(max_length=200)),
                ('role_details', models.TextField()),
                ('responsibilities', models.TextField()),
                ('key_objectives', models.TextField()),
                ('expertise', models.CharField(max_length=200)),
                ('benefits', models.TextField()),
                ('opportunity_type', models.CharField(choices=[('Co-Founder Role', 'Co-Founder Role'), ('Advisor', 'Advisor'), ('Investor Partnership', 'Investor Partnership'), ('Team Member', 'Team Member'), ('Other', 'Other')], max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('stage', models.CharField(max_length=50)),
                ('company_mission', models.TextField()),
                ('requirements', models.CharField(max_length=200)),
                ('compensation', models.CharField(choices=[('Equity-Based', 'Equity-Based'), ('Paid Opportunity', 'Paid Opportunity'), ('Other', 'Other')], max_length=50)),
                ('equity_percentage', models.FloatField(blank=True, null=True)),
                ('other_compensation', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('location_details', models.CharField(blank=True, max_length=200, null=True)),
                ('commitment', models.CharField(max_length=50)),
                ('future_plans', models.TextField()),
                ('terms', models.BooleanField(default=False)),
                ('nda', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
    ]
