# Generated by Django 5.1.4 on 2025-01-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_coreopportunity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreopportunity',
            name='commitment',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Intern', 'Intern')], max_length=50),
        ),
        migrations.AlterField(
            model_name='coreopportunity',
            name='location',
            field=models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Onsite', 'Onsite')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coreopportunity',
            name='stage',
            field=models.CharField(choices=[('Idea', 'Idea'), ('Building', 'Building'), ('MVP', 'MVP'), ('Funded', 'Funded')], max_length=50),
        ),
    ]
