# Generated by Django 5.1.4 on 2025-01-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_individualprofileupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
