from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('individual/login/', views.individual_login, name='individual_login'),
    path('individual/signup/', views.individual_signup, name='individual_signup'),
    path('individual/dashboard/', views.individual_dashboard, name='individual_dashboard'),
    path('company/login/', views.company_login, name='company_login'),
    path('company/signup/', views.company_signup, name='company_signup'),
    path('company/dashboard/', views.company_dashboard, name='company_dashboard'),
    path('logout/', views.logout_view, name='logout'),
    path('ideaform/', views.ideaform, name='ideaform'),
    path('submit_idea/', views.submit_idea, name='submit_idea'),
    path('individual/dashboard/ideasandinvest/', views.ideas_and_invest, name='ideasandinvest'),
    path('company/dashboard/myjobs/', views.myjobs, name='myjobs'),
    path('company/dashboard/myjobs/post/', views.post_job, name='post_job'),
    path('company/dashboard/myprojects/', views.myprojects, name='myprojects'),
    path('company/dashboard/myprojects/post_project/', views.myprojectform, name='myprojectform'),
    path('company/dashboard/myjobs/post/create-job/', views.post_job, name='create_job'),
    path('company/dashboard/myprojects/post_project/submit/', views.post_project, name='post_project'),
    path('delete-project/<int:project_id>/', views.delete_project, name='delete_project'),
    path('company/dashboard/myprojects/edit/<int:project_id>/', views.edit_project, name='edit_project'),
    path('explore-all-ideas/', views.explore_all_ideas, name='explore_all_ideas'),
    path('idea-detail/<int:idea_id>/', views.idea_detail, name='idea_detail'),
    path('company/dashboard/myjobs/edit/<int:job_id>/', views.edit_job, name='edit_job'),
    path('delete_job/<int:job_id>/', views.delete_job, name='delete_job'),
    path('company/dashboard/myprojects/explore/', views.explore_projects, name='explore_projects'),
    path('individual/profile/edit', views.edit_individual_profile, name='edit_individual_profile'),
    path('individual/profile/', views.individual_profile, name='individual_profile'),
    path('company/dashboard/profile/', views.company_profile, name='company_profile'),
    path('faq',views.faq,name='faq'),
    path('project/<int:project_id>/bid/', views.place_project_bid, name='place_project_bid'),
    path('company/dashboard/myportfolio/', views.myportfolio, name='myportfolio'),
    path('company/dashboard/myportfolio/all_jobs/', views.all_jobs, name='all_jobs'),
    path('company/dashboard/myportfolio/all-projects/', views.all_projects, name='all_projects'),
    path('company/dashboard/myportfolio/all-ideas/', views.all_ideas, name='all_ideas'),
    path('company/dashboard/myinternships/', views.myinternships, name='myinternships'),
    path('company/dashboard/myinternships/post_internship', views.post_internship, name='post_internship'),
    path('company/dashboard/myinternships/edit/<int:internship_id>/', views.edit_internship, name='edit_internship'),
    path('delete_internship/<int:internship_id>/', views.delete_internship, name='delete_internship'),
    path('company/dashboard/freelance',views.freelance, name='freelance'),
    path('company/dashboard/freelance/post_freelance',views.post_freelance, name='post_freelance'),
    path('company/dashboard/freelance/post_freelance/preview_freelance_project',views.preview_freelance_project, name='preview_freelance_project'),
    path('company/dashboard/project_success',views.project_success, name='project_success'),
    path('dashboard/edit-freelance/<int:project_id>/', views.edit_freelance, name='edit_freelance'),
    path('dashboard/delete-freelance/<int:project_id>/', views.delete_freelance, name='delete_freelance'),
    path("projects/<int:project_id>/bids/", views.view_bids, name="view_bids"),
    path('company/dashboard/myportfolio/all-internships/', views.all_internships, name='all_internships'),
    path('individual/dashboard/all_freelance_projects/', views.all_freelance_projects, name='all_freelance_projects'),
    path('individual/dashboard/all_freelance_projects/place-bid/<int:project_id>/', views.place_freelance_bid, name='place_freelance_bid'),
    path('freelance-project/<int:project_id>/place-bid/', 
         views.place_freelance_bid, name='place_freelance_bid'),
    path('freelance-project/<int:project_id>/my-bid/', 
         views.view_my_freelance_bid, name='view_my_freelance_bid'),
     path('company/dashboard/myportfolio/all_freelance_projects_company',views.all_freelance_projects_company,name='all_freelance_projects_company'),
     path('company/dashboard/myportfolio/all_freelance_projects_company/freelance-project/<int:project_id>/bids/', views.view_freelance_bids, name='view_freelance_bids'),
     path('individual/dashboard/individual_alljobs/', views.individual_alljobs, name='individual_alljobs'),
     path('individual/dashboard/individual_alljobs/apply_job/<int:job_id>/', views.apply_job, name='apply_job'),
     path('job_success/',views.job_success,name="job_success"),
     path('company/dashboard/myportfolio/all_jobs/view_applications/<int:job_id>/',views.view_applications,name='view_applications'),
     path('save-application/<int:app_id>/', views.save_application, name='save_application'),
     path('saved-applications/', views.saved_applications, name='saved_applications'),
     path('update-category/<int:saved_id>/', views.update_category, name='update_category'),
     path('like/<int:idea_id>/', views.like_idea, name='like_idea'),
     path('core/', views.core_view, name='core'),  # Core page with the button
     path('coreform/', views.core_form_view, name='coreform'),
     path('opportunity/<int:pk>/', views.opportunity_detail, name='opportunity_detail'),
     path('dislike/<int:idea_id>/', views.dislike_idea, name='dislike_idea'),
     path('delete_opportunity/<int:pk>/', views.delete_opportunity, name='delete_opportunity'),
     path('resume-database/', views.resume_database, name='resume_database'),
     path('explore-ideas-individual',views.explore_all_ideas_individual,name='explore_all_ideas_individual'),
     path('idea-detail-individual/<int:idea_id>/', views.idea_detail_individual, name='idea_detail_individual'),
     path('myjobs-individual',views.myjobs_individual,name='myjobs_individual'),
     path('delete-idea/<int:idea_id>/', views.delete_idea, name='delete_idea'),
     path('individual/dashboard/individual_allinternships/', views.individual_allinternships, name='individual_allinternships'),
     path('individual/dashboard/individual_allinternships/apply-internship/<int:internship_id>/', views.apply_internship, name='apply_internship'),
     path('internship-success/', views.internship_success, name='internship_success'),
     path('internship-applications/<int:internship_id>/', views.view_internship_applications, name='view_internship_applications'),
     path('save-applicant/<int:application_id>/', views.save_applicant, name='save_applicant'),
     path('bookmark/<str:item_type>/<int:item_id>/', views.toggle_bookmark, name='toggle_bookmark'),
    path('bookmarks/', views.bookmarked_items, name='bookmarked_items'),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)